DROP DATABASE IF EXISTS dat_xe_ve_que;
CREATE DATABASE dat_xe_ve_que CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dat_xe_ve_que;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','DISPATCHER','ACCOUNTANT','DRIVER','CUSTOMER') NOT NULL,
  status ENUM('ACTIVE','LOCKED') NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE customers (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL UNIQUE, name VARCHAR(255) NOT NULL, phone VARCHAR(50) NOT NULL, zalo_phone VARCHAR(50) NULL, note TEXT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE drivers (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL UNIQUE, name VARCHAR(255) NOT NULL, phone VARCHAR(50) NOT NULL, zalo_phone VARCHAR(50), status VARCHAR(100) DEFAULT 'Rảnh', current_location VARCHAR(255), direction_preference VARCHAR(255), seats_free INT DEFAULT 0, note TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE vehicles (id INT AUTO_INCREMENT PRIMARY KEY, driver_id INT NOT NULL, vehicle_type VARCHAR(100) NOT NULL, seats INT NOT NULL, license_plate VARCHAR(50), status VARCHAR(100) DEFAULT 'Đang hoạt động', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (driver_id) REFERENCES drivers(id));
CREATE TABLE locations (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, slug VARCHAR(255) UNIQUE NOT NULL, type VARCHAR(50) NOT NULL, parent_id INT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE routes (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, slug VARCHAR(255) UNIQUE NOT NULL, from_name VARCHAR(255) NOT NULL, to_name VARCHAR(255) NOT NULL, direction VARCHAR(255) NOT NULL, distance_km DECIMAL(8,2), estimated_duration_min INT, seo_title VARCHAR(255), seo_description TEXT, content LONGTEXT, status VARCHAR(100) DEFAULT 'Đang chạy', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE services (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, slug VARCHAR(255) UNIQUE NOT NULL, type ENUM('SHARED_RIDE','PRIVATE_RIDE','CARGO','MARKET','CONTRACT','WEDDING','TOUR','HOSPITAL','AIRPORT') UNIQUE NOT NULL, description TEXT, status VARCHAR(100) DEFAULT 'Đang bật', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE price_rules (id INT AUTO_INCREMENT PRIMARY KEY, service_type ENUM('SHARED_RIDE','PRIVATE_RIDE','CARGO','MARKET','CONTRACT','WEDDING','TOUR','HOSPITAL','AIRPORT') NOT NULL, route_id INT NULL, vehicle_type VARCHAR(100), pricing_type VARCHAR(50) NOT NULL, base_price DECIMAL(12,2) DEFAULT 0, price_per_person DECIMAL(12,2) DEFAULT 0, price_per_kg DECIMAL(12,2) DEFAULT 0, commission_type VARCHAR(50) DEFAULT 'FIXED', commission_value DECIMAL(12,2) DEFAULT 0, active BOOLEAN DEFAULT TRUE, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (route_id) REFERENCES routes(id));
CREATE TABLE bookings (id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(50) UNIQUE NOT NULL, customer_id INT NULL, customer_name VARCHAR(255) NOT NULL, customer_phone VARCHAR(50) NOT NULL, type ENUM('SHARED_RIDE','PRIVATE_RIDE','CARGO','MARKET','CONTRACT','WEDDING','TOUR','HOSPITAL','AIRPORT') NOT NULL, route_id INT NULL, direction VARCHAR(255), pickup_address VARCHAR(500), dropoff_address VARCHAR(500), scheduled_at DATETIME NULL, passenger_count INT DEFAULT 1, vehicle_type VARCHAR(100), cargo_description TEXT, market_description TEXT, note TEXT, status ENUM('NEW','CONTACTED','QUOTED','WAITING_DEPOSIT','DEPOSITED','WAITING_DISPATCH','ASSIGNED','DRIVER_ACCEPTED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW') DEFAULT 'NEW', estimated_total DECIMAL(12,2) DEFAULT 0, final_total DECIMAL(12,2) DEFAULT 0, commission_amount DECIMAL(12,2) DEFAULT 0, payment_receiver VARCHAR(50) DEFAULT 'DRIVER', source VARCHAR(50) DEFAULT 'WEBSITE', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (customer_id) REFERENCES customers(id), FOREIGN KEY (route_id) REFERENCES routes(id));
CREATE TABLE trips (id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(50) UNIQUE NOT NULL, route_id INT NOT NULL, driver_id INT NULL, vehicle_id INT NULL, departure_at DATETIME NOT NULL, total_seats INT DEFAULT 0, booked_seats INT DEFAULT 0, available_seats INT DEFAULT 0, status ENUM('COLLECTING','READY','IN_PROGRESS','COMPLETED','CANCELLED') DEFAULT 'COLLECTING', total_customer_amount DECIMAL(12,2) DEFAULT 0, admin_commission DECIMAL(12,2) DEFAULT 0, driver_net_amount DECIMAL(12,2) DEFAULT 0, driver_debt_amount DECIMAL(12,2) DEFAULT 0, settlement_status ENUM('PENDING','PARTIAL','PAID','RECONCILED','WAIVED','DISPUTED') DEFAULT 'PENDING', note TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(route_id) REFERENCES routes(id), FOREIGN KEY(driver_id) REFERENCES drivers(id), FOREIGN KEY(vehicle_id) REFERENCES vehicles(id));
CREATE TABLE trip_bookings (id INT AUTO_INCREMENT PRIMARY KEY, trip_id INT NOT NULL, booking_id INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY trip_booking_unique (trip_id, booking_id), FOREIGN KEY(trip_id) REFERENCES trips(id), FOREIGN KEY(booking_id) REFERENCES bookings(id));
CREATE TABLE driver_settlement_payments (id INT AUTO_INCREMENT PRIMARY KEY, trip_id INT NULL, driver_id INT NOT NULL, amount DECIMAL(12,2) NOT NULL, direction VARCHAR(50) NOT NULL, method VARCHAR(50) NOT NULL, note TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE site_settings (id INT AUTO_INCREMENT PRIMARY KEY, `key` VARCHAR(100) UNIQUE NOT NULL, value TEXT, group_name VARCHAR(100) DEFAULT 'general', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE media_files (id INT AUTO_INCREMENT PRIMARY KEY, original_name VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_url VARCHAR(500) NOT NULL, mime_type VARCHAR(100) NOT NULL, size_bytes INT NOT NULL, alt_text VARCHAR(255) NOT NULL, title VARCHAR(255), usage_type VARCHAR(100) NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE post_categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, slug VARCHAR(255) UNIQUE NOT NULL);
CREATE TABLE posts (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, slug VARCHAR(255) UNIQUE NOT NULL, excerpt TEXT, content LONGTEXT NOT NULL, category_id INT NULL, status VARCHAR(50) DEFAULT 'DRAFT', published_at DATETIME NULL, seo_title VARCHAR(255), seo_description TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES post_categories(id));

INSERT INTO users (id,name,phone,email,password_hash,role,status) VALUES
(1,'Admin Đặt Xe','0900000000','admin@datxeveque.vn','admin123','ADMIN','ACTIVE'),
(2,'Anh Tài Xế Một','0900000001','taixe@datxeveque.vn','taixe123','DRIVER','ACTIVE'),
(3,'Khách Test','0900000002','khach@datxeveque.vn','khach123','CUSTOMER','ACTIVE');
INSERT INTO customers (id,user_id,name,phone) VALUES (1,3,'Khách Test','0900000002');
INSERT INTO drivers (id,user_id,name,phone,status,current_location,direction_preference,seats_free) VALUES (1,2,'Anh Tài Xế Một','0900000001','Rảnh','Bình Tân','Sài Gòn → Đức Linh/Tánh Linh',4);
INSERT INTO vehicles (id,driver_id,vehicle_type,seats,license_plate) VALUES (1,1,'Xe 7 chỗ',7,'86A-12345');
INSERT INTO routes (id,name,slug,from_name,to_name,direction,distance_km,estimated_duration_min,seo_title,seo_description,content) VALUES
(1,'Xe Sài Gòn đi Đức Linh','xe-sai-gon-di-duc-linh','Sài Gòn','Đức Linh','Sài Gòn → Đức Linh',150,240,'Xe Sài Gòn đi Đức Linh | Xe ghép, bao xe, gửi hàng','Đặt xe Sài Gòn đi Đức Linh, nhận xe ghép, bao xe 4-7 chỗ, gửi hàng, đi chợ quê.','Tuyến Sài Gòn đi Đức Linh hỗ trợ xe ghép, bao xe, gửi hàng và đi chợ quê.'),
(2,'Xe Đức Linh đi Sài Gòn','xe-duc-linh-di-sai-gon','Đức Linh','Sài Gòn','Đức Linh → Sài Gòn',150,240,'Xe Đức Linh đi Sài Gòn | Đón trả tận nơi','Đặt xe Đức Linh đi Sài Gòn, hỗ trợ khách về lại thành phố.','Tuyến Đức Linh đi Sài Gòn hỗ trợ nhiều khung giờ.'),
(3,'Xe Sài Gòn đi Tánh Linh','xe-sai-gon-di-tanh-linh','Sài Gòn','Tánh Linh','Sài Gòn → Tánh Linh',178,270,'Xe Sài Gòn đi Tánh Linh | Xe ghép, bao xe','Đặt xe Sài Gòn đi Tánh Linh, xe ghép, bao xe, gửi hàng.','Tuyến Sài Gòn đi Tánh Linh hỗ trợ Lạc Tánh, Bắc Ruộng, Đồng Kho.'),
(4,'Xe Tánh Linh đi Sài Gòn','xe-tanh-linh-di-sai-gon','Tánh Linh','Sài Gòn','Tánh Linh → Sài Gòn',178,270,'Xe Tánh Linh đi Sài Gòn | Đặt xe nhanh','Đặt xe Tánh Linh đi Sài Gòn, hỗ trợ đón trả tận nơi.','Tuyến Tánh Linh đi Sài Gòn hỗ trợ khách, hàng hóa và xe riêng.');
INSERT INTO services (name,slug,type,description) VALUES
('Xe ghép','xe-ghep','SHARED_RIDE','Gom khách theo tuyến cố định'),('Bao xe','bao-xe','PRIVATE_RIDE','Xe riêng 4-7-16 chỗ'),('Gửi hàng','gui-hang','CARGO','Gửi hàng hai chiều'),('Đi chợ quê','di-cho-que','MARKET','Mua hộ đồ quê'),('Xe hợp đồng','xe-hop-dong','CONTRACT','Thuê xe theo lịch trình');
INSERT INTO price_rules (service_type,route_id,pricing_type,base_price,price_per_person,price_per_kg,commission_type,commission_value) VALUES
('SHARED_RIDE',1,'PER_PERSON',0,250000,0,'FIXED',30000),('SHARED_RIDE',2,'PER_PERSON',0,250000,0,'FIXED',30000),('SHARED_RIDE',3,'PER_PERSON',0,280000,0,'FIXED',35000),('SHARED_RIDE',4,'PER_PERSON',0,280000,0,'FIXED',35000),('PRIVATE_RIDE',1,'PER_TRIP',1200000,0,0,'FIXED',150000),('CARGO',1,'PER_KG',30000,0,5000,'FIXED',20000),('MARKET',NULL,'PER_TRIP',50000,0,0,'FIXED',20000),('CONTRACT',NULL,'PER_TRIP',1000000,0,0,'PERCENT',10);
INSERT INTO bookings (id,code,customer_id,customer_name,customer_phone,type,route_id,direction,pickup_address,dropoff_address,scheduled_at,passenger_count,status,estimated_total,final_total,commission_amount,payment_receiver) VALUES
(1,'DX000001',1,'Khách Test','0900000002','SHARED_RIDE',1,'Sài Gòn → Đức Linh','Bình Tân','Võ Xu',DATE_ADD(NOW(), INTERVAL 1 DAY),2,'ASSIGNED',500000,500000,60000,'DRIVER');
INSERT INTO trips (id,code,route_id,driver_id,vehicle_id,departure_at,total_seats,booked_seats,available_seats,status,total_customer_amount,admin_commission,driver_net_amount,driver_debt_amount,settlement_status) VALUES
(1,'CX000001',1,1,1,DATE_ADD(NOW(), INTERVAL 1 DAY),5,2,3,'COLLECTING',500000,60000,440000,60000,'PENDING');
INSERT INTO trip_bookings (trip_id,booking_id) VALUES (1,1);
INSERT INTO site_settings (`key`,value,group_name) VALUES
('brand_name','Đặt Xe Về Quê','general'),('slogan','Dịch vụ vận chuyển quê nhà chuyên nghiệp','general'),('hotline_primary','0900000000','contact'),('zalo_url','https://zalo.me/0900000000','contact'),('facebook_page_url','https://facebook.com/datxeveque','contact'),('email','hotro@datxeveque.vn','contact'),('service_area','Sài Gòn, Đức Linh, Tánh Linh','contact');
INSERT INTO post_categories (id,name,slug) VALUES (1,'Kinh nghiệm đặt xe','kinh-nghiem-dat-xe'),(2,'Gửi hàng về quê','gui-hang-ve-que');
INSERT INTO posts (title,slug,excerpt,content,category_id,status,published_at,seo_title,seo_description) VALUES
('Sài Gòn đi Đức Linh bao nhiêu km, mất bao lâu?','sai-gon-di-duc-linh-bao-nhieu-km','Tổng quan thời gian di chuyển, cách đặt xe và lưu ý khi về Đức Linh.','<p>Tuyến Sài Gòn đi Đức Linh phù hợp cho khách về quê cuối tuần, gửi hàng và đi bệnh viện.</p><h2>Có nên đặt xe trước?</h2><p>Nên đặt trước để hệ thống gom khách và sắp tài xế phù hợp.</p>',1,'PUBLISHED',NOW(),'Sài Gòn đi Đức Linh bao nhiêu km?','Kinh nghiệm đặt xe Sài Gòn đi Đức Linh, thời gian di chuyển và lưu ý.'),
('Gửi hàng Sài Gòn Đức Linh cần lưu ý gì?','gui-hang-sai-gon-duc-linh-can-luu-y-gi','Lưu ý đóng gói hàng quê, đồ ăn, rau củ, giấy tờ khi gửi xe.','<p>Hàng nên đóng gói kỹ, ghi rõ người gửi/người nhận và số điện thoại.</p>',2,'PUBLISHED',NOW(),'Gửi hàng Sài Gòn Đức Linh cần lưu ý gì?','Hướng dẫn gửi hàng từ Sài Gòn về Đức Linh và chiều ngược lại.');
